/* Reader's Haven - Manga Data Store */

window.MangaData = {
  carouselData: [
    {
      title: "THE EMINENCE IN SHADOW",
      demo: "shounen",
      chapter: "Chapter 1",
      desc: "Cid's dream is to become a mastermind who pulls strings in the shadows. Reincarnated into a fantasy world, he creates an imaginary organization to fight a cult... only for that cult to actually exist!",
      status: "ONGOING",
      genres: ["Action", "Comedy", "Fantasy", "Isekai"],
      img: "./manga-art/Kage no Jitsuryokusha ni Naritakute!.jpg",
      type: "manga",
      chapters: [
        {
          id: "eis-1",
          title: "Chapter 1: The Eminence in Shadow!",
          pages: 0,
          source:
            "/manga-source/Kage no Jitsuryokusha ni Naritakute! - Ch. 1.pdf",
          type: "pdf",
        },
      ],
    },
    {
      title: "ATTACK ON TITAN",
      chapter: "Chapter 139: Toward the Tree on That Hill",
      desc: "The final, world-shaking battle reaches its definitive conclusion. A world without walls awaits in the epic finale to Hajime Isayama's masterpiece.",
      status: "COMPLETED",
      genres: ["Action", "Drama", "Mystery"],
      img: "./manga-art/attack_on_titan.jpg",
      type: "manga",
      chapters: [
        {
          id: "aot-139",
          title: "Chapter 139: Toward the Tree on That Hill",
          pages: 20,
        },
        { id: "aot-138", title: "Chapter 138: A Long Dream", pages: 18 },
        { id: "aot-137", title: "Chapter 137: Titans", pages: 16 },
        {
          id: "aot-2",
          title: "Chapter 2: The World of the Titans",
          pages: 41,
          source: "/manga-source/chapter_2-Attack_on_Titan.pdf",
          type: "pdf",
        },
        {
          id: "aot-1",
          title: "Chapter 1: To You, 2000 Years From   Now",
          pages: 51,
          source: "/manga-source/chapter_1-Attack_on_Titan.pdf",
          type: "pdf",
        },
      ],
    },
    {
      title: "SOLO LEVELING",
      chapter: "Chapter 179 (COMPLETED)",
      desc: "The final battle against the Monarchs.<br><br>Sung Jinwoo faces his greatest challenge yet in this epic conclusion.",
      status: "COMPLETED",
      genres: ["Action", "Fantasy", "System"],
      img: "./manga-art/solo_leveling.jpg",
      type: "manhwa",
      chapters: [
        { id: "sl-179", title: "Chapter 179: Epilogue finale", pages: 15 },
        {
          id: "sl-178",
          title: "Chapter 178: The Monarch of Shadows",
          pages: 12,
        },
        {
          id: "sl-1",
          title: "Chapter 1: The Courage of the Weakest",
          pages: 18,
        },
      ],
    },
    {
      title: "CHAINSAW MAN",
      chapter: "Chapter 131",
      desc: "Denji's chaotic life continues as new devils appear in the city. High-octane action and dark comedy awaits.",
      status: "ONGOING",
      genres: ["Action", "Supernatural", "Gore"],
      img: "./manga-art/chainsaw_man.jpg",
      type: "manga",
      chapters: [
        {
          id: "csm-1",
          title: "Chapter 232 [END]",
          source: "/manga-source/chapter_232-Chainsaw_Man.pdf",
          pages: 23,
        },
        {
          id: "csm-1",
          title: "Chapter 231:",
          source: "/manga-source/chapter_231-Chainsaw_Man.pdf",
          pages: 23,
        },
        {
          id: "csm-1",
          title: "Chapter 3",
          source: "/manga-source/chapter_3-Chainsaw_Man.pdf",
          pages: 23,
        },
        {
          id: "csm-1",
          title: "Chapter 2",
          source: "/manga-source/chapter_2-Chainsaw_Man.pdf",
          pages: 26,
        },
        {
          id: "csm-1",
          title: "Chapter 1",
          source: "/manga-source/chapter_1-Chainsaw_Man.pdf",
          pages: 57,
        },
      ],
    },
    {
      title: "Blue Lock: Episode Nagi",
      ch: "Ch. 215",
      rating: 4.7,
      views: "9.2k",
      isNew: true,
      type: "manga",
      img: "./manga-art/blue_lock_episode_nagi.jpg",
      genres: ["Action", "Supernatural", "Gore"],
      chapters: [
        {
          id: "bl-4",
          title: "Chapter 4: A Game",
          source: "/manga-source/Blue_Lock-Episode_Nagi-Ch.4-El juego.pdf",
          pages: 36,
          type: "pdf",
        },
        {
          id: "bl-3",
          title: "Chapter 3: Idiot",
          source: "/manga-source/Blue_Lock-Episode_Nagi-Ch.3-Estúpido.pdf",
          pages: 33,
          type: "pdf",
        },
        {
          id: "bl-2",
          title: "Chapter 2: Promise",
          source: "/manga-source/Blue_Lock-Episod_Nagi-Ch.2-Promesa.pdf",
          pages: 52,
          type: "pdf",
        },
        {
          id: "bl-1",
          title: "Chapter 1: A Genius",
          source:
            "/manga-source/Blue_Lock-Episode_Nagi-Ch.1-Un_verdadero_prodigio.pdf",
          pages: 61,
          type: "pdf",
        },
      ],
    },
  ],

  gridData: [
    // ── MANGA ────────────────────────────────────────────────────────────────
    {
      title: "The Eminence in Shadow",
      ch: "Ch. 1",
      rating: 4.9,
      views: "15.4k",
      isNew: true,
      type: "manga",
      img: "./manga-art/Kage no Jitsuryokusha ni Naritakute!.jpg",
      chapters: [
        {
          id: "eis-1",
          title: "Chapter 1: The Eminence in Shadow!",
          pages: 0,
          source:
            "/manga-source/Kage no Jitsuryokusha ni Naritakute! - Ch. 1.pdf",
          type: "pdf",
        },
      ],
    },
    {
      title: "Attack on Titan",
      ch: "Ch. 139",
      desc: "In this post-apocalyptic sci-fi story, humanity has been devastated by the bizarre, giant humanoids known as the Titans. Little is known about where they came from or why they are bent on consuming mankind. Seemingly unintelligent, they have roamed the world for years, killing everyone they see. For the past century, what’s left of man has hidden in a giant, three-walled city. People believe their 100-meter high walls will protect them from the Titans, but the sudden appearance of an immense Titan is about to change everything.",
      rating: 5.0,
      views: "25.5k",
      isNew: true,
      type: "manga",
      img: "./manga-art/attack_on_titan.jpg",
      chapters: [
        {
          id: "aot-139",
          title: "Chapter 139: Toward the Tree on That Hill",
          pages: 20,
        },
        { id: "aot-138", title: "Chapter 138: A Long Dream", pages: 18 },
        { id: "aot-137", title: "Chapter 137: Titans", pages: 16 },
        {
          id: "aot-2",
          title: "Chapter 2: The World of the Titans",
          pages: 41,
          source: "/manga-source/chapter_2-Attack_on_Titan.pdf",
          type: "pdf",
        },
        {
          id: "aot-1",
          title: "Chapter 1: To You, 2000 Years From   Now",
          pages: 51,
          source: "/manga-source/chapter_1-Attack_on_Titan.pdf",
          type: "pdf",
        },
      ],
    },
    {
      title: "Chainsaw Man",
      ch: "Ch. 131",
      rating: 4.8,
      views: "13.1k",
      isNew: true,
      type: "manga",
      img: "./manga-art/chainsaw_man.jpg",
      genres: ["Comedy", "Drama", "Horror"],
      chapters: [
        {
          id: "csm-1",
          title: "Chapter 232 [END]",
          source: "/manga-source/chapter_232-Chainsaw_Man.pdf",
          pages: 23,
        },
        {
          id: "csm-1",
          title: "Chapter 231",
          source: "/manga-source/chapter_231-Chainsaw_Man.pdf",
          pages: 14,
        },
        {
          id: "csm-1",
          title: "Chapter 3",
          source: "/manga-source/chapter_3-Chainsaw_Man.pdf",
          pages: 23,
        },
        {
          id: "csm-1",
          title: "Chapter 2",
          source: "/manga-source/chapter_2-Chainsaw_Man.pdf",
          pages: 26,
        },
        {
          id: "csm-1",
          title: "Chapter 1",
          source: "/manga-source/chapter_1-Chainsaw_Man.pdf",
          pages: 57,
        },
      ],
    },
    {
      title: "One Piece",
      demo: "shounen",
      ch: "Ch. 1185",
      rating: 4.5,
      views: "15.5k",
      isNew: true,
      type: "manga",
      genres: ["Action", "Adventure", "Comedy", "Drama"],
      img: "./manga-art/one_piece.jpg",
      chapters: [
        {
          id: "op-4",
          title: "Chapter 4: The Great Captain Morgan",
          pages: 20,
          source: "/manga-source/chapter_4-One_Piece.pdf",
          type: "pdf",
        },
        {
          id: "op-3",
          title: "Chapter 3: Enter Zoro: Pirate Hunter",
          pages: 22,
          source: "/manga-source/chapter_3-One_Piece.pdf",
          type: "pdf",
        },
        {
          id: "op-2",
          title: "Chapter 2: They call him Straw Hat Luffy",
          pages: 24,
          source: "/manga-source/chapter_2-One_Piece.pdf",
          type: "pdf",
        },
        {
          id: "op-1",
          title: "Chapter 1: Romance Dawn",
          pages: 57,
          source: "/manga-source/chapter_1-One_Piece.pdf",
          type: "pdf",
        },
      ],
    },

    {
      title: "Blue Lock: Episode Nagi",
      demographic: "shounen",
      ch: "Ch. 215",
      rating: 4.7,
      views: "9.2k",
      isNew: true,
      type: "manga",
      status: "ONGOING",
      img: "./manga-art/blue_lock_episode_nagi.jpg",
      genres: ["Sport", "Drama"],
      chapters: [
        {
          id: "bl-4",
          title: "Chapter 4: A Game",
          source: "/manga-source/Blue_Lock-Episode_Nagi-Ch.4-El juego.pdf",
          pages: 36,
          type: "pdf",
        },
        {
          id: "bl-3",
          title: "Chapter 3: Idiot",
          source: "/manga-source/Blue_Lock-Episode_Nagi-Ch.3-Estúpido.pdf",
          pages: 33,
          type: "pdf",
        },
        {
          id: "bl-2",
          title: "Chapter 2: Promise",
          source: "/manga-source/Blue_Lock-Episod_Nagi-Ch.2-Promesa.pdf",
          pages: 52,
          type: "pdf",
        },
        {
          id: "bl-1",
          title: "Chapter 1: A Genius",
          source:
            "/manga-source/Blue_Lock-Episode_Nagi-Ch.1-Un_verdadero_prodigio.pdf",
          pages: 61,
          type: "pdf",
        },
      ],
    },
    {
      title: "Naruto",
      demo: "shounen",
      ch: "Ch. 700",
      rating: 4.9,
      views: "14.5k",
      isNew: true,
      type: "manga",
      status: "COMPLETED",
      genres: ["Adventure", "Drama", "Comedy"],
      img: "./manga-art/naruto.jpg",
      chapters: [
        {
          id: "n-1",
          title: "Chapter 700: Uzumaki Naruto!! [END]",
          source: "/manga-source/chapter_700-naruto",
          pages: 22,
          type: "pdf",
        },
        {
          id: "n-1",
          title: "Chapter 2: Konohamaru",
          source: "/manga-source/chapter_2-naruto",
          pages: 22,
          type: "pdf",
        },
        {
          id: "n-1",
          title: "Chapter 1: Uzumaki Naruto!",
          source: "/manga-source/chapter_1-naruto.pdf",
          pages: 58,
          type: "pdf",
        },
      ],
    },
    {
      title: "JoJo's Bizarre Adventure - Part 1 - Phantom Blood",
      ch: "Ch. 44",
      rating: 4.5,
      views: "10.8k",
      isNew: true,
      type: "manga",
      status: "COMPLETED",
      genres: ["Drama", "Adventure", "Horror"],
      img: "./manga-art/jojo_phantom_blood.jpg",
      chapters: [
        {
          id: "jojo-1",
          title: "Chapter 44: Fire and Ice, Jonathan and Dio Part 6 [END]",
          source: "/manga-source/chapter_44-jojo1.pdf",
          pages: 22,
          type: "pdf",
        },
        {
          id: "jojo-1",
          title: "Chapter 43: Fire and Ice, Jonathan and Dio Part 5",
          source: "/manga-source/chapter_43-jojo1.pdf",
          pages: 19,
          type: "pdf",
        },
        {
          id: "jojo-1",
          title: "Chapter 3: Dio Brando the Invader Part 2",
          source: "/manga-source/chapter_3-jojo1.pdf",
          pages: 21,
          type: "pdf",
        },
        {
          id: "jojo-1",
          title: "Chapter 2: Dio Brando the Invader Part 1",
          source: "/manga-source/chapter_2-jojo1.pdf",
          pages: 23,
          type: "pdf",
        },
        {
          id: "jojo-1",
          title: "Chapter 1: Prologue",
          source: "/manga-source/chapter_1-jojo1.pdf",
          pages: 34,
          type: "pdf",
        },
      ],
    },
    {
      title: "Nana",
      desc: "Nana (Hachi) Komatsu hopes that moving to Tokyo will help her make a clean start and leave her capricious love life behind her. Nana Osaki, who arrives in the city at the same time, has plans to score big in the world of rock 'n' roll. Although these two young women come from different backgrounds, they quickly become best friends in a whirlwind world of sex, music, fashion, gossip, and all-night parties!",
      demo: "shoujo",
      ch: "Ch. 21",
      rating: 4.5,
      views: "10.8k",
      isNew: true,
      type: "manga",
      status: "HIATUS",
      genres: ["Drama", "Romance", "Comedy"],
      img: "./manga-art/nana.jpg",
      chapters: [
        {
          id: "nana-1",
          title: "Chapter 1",
          source: "/manga-source/chapter_1-nana.pdf",
          pages: 180,
          type: "pdf",
        },
      ],
    },
    {
      title: "Maid-sama!",
      demo: "shoujo",
      desc: "Brilliant and overachieving, Misaki Ayuzawa is the President of the Student Council at Seika High School, formerly a boys' school. Unfortunately, most of the students are still male and stuck in their slovenly habits, so man-hating Misaki really socks it to 'em in an attempt to make the school presentable to attract more female students. But what will she do when the sexiest boy in school finds out that after school, Misaki works in a maid cafe.",
      ch: "Ch. 85",
      rating: 4.6,
      views: "40.1k",
      isNew: true,
      type: "manga",
      status: "COMPLETED",
      genres: ["Drama", "Romance", "Comedy"],
      img: "./manga-art/maid_sama.jpg",
      chapters: [
        {
          id: "ms-1",
          title: "Chapter 1: The Student Council President is a Maid!",
          source: "/manga-source/chapter_1-maidsama.pdf",
          pages: 37,
          type: "pdf",
        },
      ],
    },
    {
      title: "Dragon Ball",
      demo: "shounen",
      desc: "Dragon Ball follows the adventures of Son Goku from his childhood through adulthood as he trains in martial arts and explores the world in search of the seven mystical orbs known as the Dragon Balls, which can summon a wish-granting dragon when gathered. Along his journey, Goku makes several friends and battles a wide variety of villains, many of whom also seek the Dragon Balls for their own desires. Along the way becoming the strongest warrior in the universe.",
      ch: "Ch. 325",
      rating: 4.7,
      views: "45.5k",
      isNew: true,
      type: "manga",
      status: "COMPLETED",
      genres: ["Adventure", "Sci-fi", "Comedy"],
      img: "./manga-art/dragonball.jpg",
      showVolumes: false,
      chapters: [
        {
          id: "db-3",
          title: "Chapter 3: Sea Monkeys",
          pages: 14,
          source: "/manga-source/chapter_3-Dragon_Ball.pdf",
          type: "pdf",
        },
        {
          id: "db-2",
          title: "Chapter 2: No Balls!",
          pages: 14,
          source: "/manga-source/chapter_2-Dragon_Ball.pdf",
          type: "pdf",
        },
        {
          id: "db-1",
          title: "Chapter 1: Bloomers and the Monkey King (Bulma and Son Goku)",
          pages: 47,
          source: "/manga-source/chapter_1-Dragon_Ball.pdf",
          type: "pdf",
        },
      ],
    },
    {
      title: "Tokyo Ghoul",
      demo: "seinen",
      ch: "Ch. 143",
      desc: "Strange murders are happening in Tokyo. Due to liquid evidence at the scene, the police conclude the attacks are the acts of man-eating monsters, ghouls.College buddies Kaneki and Hide come up with the idea that ghouls are imitating humans so that's why they haven't ever seen one. Little did they know that their theory may very well be reality.",
      rating: 4.8,
      views: "12.2k",
      isNew: true,
      type: "manga",
      status: "COMPLETED",
      genres: ["Drama"],
      img: "./manga-art/tokyo_ghoul.jpg",
      chapters: [
        {
          id: "tg-3",
          title: "Chapter 3: Awful",
          pages: 26,
          source: "/manga-source/chapter_3-tokyoghoul.pdf",
          type: "pdf",
        },
        {
          id: "tg-2",
          title: "Chapter 2: Oddity",
          pages: 30,
          source: "/manga-source/chapter_2-tokyoghoul.pdf",
          type: "pdf",
        },
        {
          id: "tg-1",
          title: "Chapter 1: Tragedy",
          pages: 47,
          source: "/manga-source/chapter_1-tokyoghoul.pdf",
          type: "pdf",
        },
      ],
    },
    {
      title: "Death Note",
      ch: "Ch. 108.4",
      desc: "Light Yagami is an ace student with great prospects—and he’s bored out of his mind. But all that changes when he finds the Death Note, a notebook dropped by a rogue Shinigami death god. Any human whose name is written in the notebook dies, and Light has vowed to use the power of the Death Note to rid the world of evil. But will Light succeed in his noble goal, or will the Death Note turn him into the very thing he fights against?",
      status: "COMPLETED",
      genres: ["Mystery", "Psychological", "Supernatural"],
      rating: 4.9,
      views: "30.5k",
      isNew: true,
      type: "manga",
      img: "./manga-art/death_note.jpg",
      chapters: [
        {
          id: "dn-3",
          title: "Chapter 3: Family",
          pages: 28,
          source: "/manga-source/chapter_3-deathnote.pdf",
          type: "pdf",
        },
        {
          id: "dn-2",
          title: "Chapter 2: L",
          pages: 30,
          source: "/manga-source/chapter_2-deathnote.pdf",
          type: "pdf",
        },
        {
          id: "dn-1",
          title: "Chapter 1: Boredom",
          pages: 53,
          source: "/manga-source/chapter_1-deathnote.pdf",
          type: "pdf",
        },
      ],
    },
    {
      title: "Haikyuu!! (COLOR)",
      demo: "shounen",
      decs: "A chance event triggered Shouyou Hinata's love for volleyball. His club had no members, but somehow persevered and finally made it into its very first and final regular match of middle school, where it was steamrolled by Tobio Kageyama, a superstar player known as (King of the Court.) Vowing revenge, Hinata applied to the Karasuno High School volleyball club...only to come face-to-face with his hated rival, Kageyama! A tale of hot-blooded youth and volleyball from the pen of Haruichi Furudate!!",
      ch: "Ch. 402.3",
      rating: 4.8,
      views: "11.5k",
      isNew: true,
      type: "manga",
      status: "COMPLETED",
      genres: ["sport", "comedy", "drama", "fantasy"],
      img: "./manga-art/haikyuu.jpg",
      chapters: [
        {
          id: "h-1",
          title: "Chapter 398",
          pages: 10,
          source: "/manga-source/chapter_398-haikyuu.pdf",
          type: "pdf",
        },
        {
          id: "h-1",
          title: "Chapter 397",
          pages: 14,
          source: "/manga-source/chapter_397-haikyuu.pdf",
          type: "pdf",
        },
      ],
    },
    {
      title: "The Summer Hikaru Died",
      demo: "seinen",
      desc: "Two boys lived in a village: Yoshiki and Hikaru. The two did everything together...until the day Hikaru was encompassed by a mysterious light. That was when everything changed—Hikaru most of all. Yoshiki still wishes from the bottom of his heart to always stay by his side...but is there even a Hikaru left to be with?",
      ch: "Ch. 40.3",
      rating: 3.5,
      views: "6.2k",
      isNew: true,
      type: "manga",
      status: "ONGOING",
      genres: ["horror", "mystery"],
      img: "./manga-art/the_summer_hikaru_died.jpg",
      chapters: [
        {
          id: "tshd-1",
          title: "Chapter 3",
          pages: 29,
          source: "/manga-source/chapter_3-the_summer_hikaru_died.pdf",
          type: "pdf",
        },
      ],
    },
    {
      title: "Monster",
      demo: "seinen",
      ch: "Ch. 162",
      desc: "Everyone faces uncertainty at some point in their lives. Even a brilliant surgeon like Kenzo Tenma is no exception. But there's no way he could have known that his decision to stop chasing professional success and instead concentrate on his oath to save peoples' lives would result in the birth of an abomination. The questions of good and evil now take on a terrifyingly real dimension.  Years later, in Germany during the tumultuous post-reunification period, middle-aged childless couples are being killed one after another. The serial killer's identity is known. The reasons why he kills are not. Dr. Tenma sets out on a journey to find the killer's twin sister, who may hold some clues to solving the enigma of the Monster.",
      rating: 4.4,
      views: "4.2k",
      isNew: true,
      type: "manga",
      status: "ONGOING",
      genres: ["horror", "Drama", "horror", "mystery"],
      img: "./manga-art/monster.jpg",
      chapters: [
        {
          id: "m-2",
          title: "Chapter 2: Kill",
          pages: 26,
          source: "/manga-source/chapter_2-monster.pdf",
          type: "pdf",
        },
        {
          id: "m-1",
          title: "Chapter 1: Herr Doktor Tenma",
          pages: 35,
          source: "/manga-source/chapter_1-monster.pdf",
          type: "pdf",
        },
      ],
    },
    {
      title: "Vagabond",
      demo: "hiatus",
      decs: "At seventeen years of age, Miyamoto Musashi, still known by his childhood name, Shinmen Takezō was a wild young brute just setting out along the way of the sword.",
      ch: "Ch. 327",
      rating: 5.0,
      views: "7.1k",
      isNew: true,
      type: "manga",
      status: "ONGOING",
      genres: ["Adventure", "Drama", "Action"],
      img: "./manga-art/vagabond.jpg",
      chapters: [
        {
          id: "v-1",
          title: "Chapter 1",
          pages: 45,
          source: "/manga-source/chapter_1-vagabond.pdf",
          type: "pdf",
        },
      ],
    },
    {
      title: "Berserk",
      demo: "seinen",
      decs: "His name is Guts, the Black Swordsman, a feared warrior spoken of only in whispers. Bearer of a gigantic sword, an iron hand, and the scars of countless battles and tortures, his flesh is also indelibly marked with The Brand, an unholy symbol that draws the forces of darkness to him and dooms him as their sacrifice. But Guts won't take his fate lying down; he'll cut a crimson swath of carnage through the ranks of the damned - and anyone else foolish enough to oppose him! Accompanied by Puck the Elf, more an annoyance than a companion, Guts relentlessly follows a dark, bloodstained path that leads only to death or vengeance.",
      ch: "Ch. 373",
      rating: 5.0,
      views: "25.2k",
      isNew: true,
      type: "manga",
      status: "ONGOING",
      genres: ["Adventure", "Drama", "Horror"],
      img: "./manga-art/berserk.jpg",
      chapters: [
        {
          id: "bs-1",
          title: "Prologue 1",
          pages: 93,
          source: "/manga-source/chapter_1-berserk.pdf",
          type: "pdf",
        },
      ],
    },
    {
      title: "Blood-C",
      demo: "shounen",
      decs: "Kisaragi Saya is a happy, small-town schoolgirl who spends peaceful days with her friends. She mostly hangs out with her friend Yuka, the twins Nono and Nene, and the class rep, who seems to have a crush on her. Saya is also intrigued with a mysterious loner named Tokizane, who always comes to school late. She lives at home with her widowed father, and often eats at the neighboring cafe 'Guimauve,' which is run by the excellent chef and family friend Fumito. Her life may seem very tranquil and happy from the outside, but Saya also secretly wields a mystical sword to defend the town from the 'Old Ones,' monsters who eat people. Lately, Saya is beginning to think that there's a lot more to the situation with the Old Ones than she knows...",
      ch: "Ch. 17",
      rating: 4.5,
      views: "22.5k",
      isNew: true,
      type: "manga",
      status: "COMPLETED",
      genres: ["mystery", "Drama", "Horror"],
      img: "./manga-art/blood_c.jpg",
      chapters: [
        {
          id: "bc-1",
          title: "chapter 16",
          pages: 43,
          source: "/manga-source/chapter_16-blood_c.pdf",
          type: "pdf",
        },
      ],
    },
    {
      title: "Slam Dunk",
      demo: "shounen",
      desc: "Winning isn't everything in the game of basketball, but who wants to come in second? It takes dedication and discipline to be the best, and the Shohoku High hoops team wants to be just that. They have one last year to make their captain's dream of reaching the finals come true--will they do it? Takehiko Inoue's legendary beloved basketball manga is finally here and the tale of a lifetime is in your hands.",
      ch: "Ch. 276",
      rating: 4.9,
      views: "10.1k",
      isNew: false,
      type: "manga",
      status: "COMPLETED",
      genres: ["comedy", "drama", "sport"],
      img: "./manga-art/slam_dunk.jpg",
      chapters: [
        {
          id: "sd-1",
          title: "chapter 273",
          pages: 19,
          source: "/manga-source/chapter_274-slam_dunk.pdf",
          type: "pdf",
        },
        {
          id: "sd-1",
          title: "chapter 273",
          pages: 21,
          source: "/manga-source/chapter_273-slam_dunk.pdf",
          type: "pdf",
        },
      ],
    },
    {
      title: "Sakamoto Days",
      demo: "shounen",
      desc: "Sakamoto is a former legendary hitman who has retired from the business to live a peaceful life as a family man. However, his past comes back to haunt him when he is forced to take on a new mission that puts his skills to the test. With his trusty sidekick, a young girl named Hana, Sakamoto must navigate the dangerous world of assassins and criminals while trying to protect his loved ones. Will he be able to complete his mission and keep his family safe?",
      ch: "Ch. 259",
      rating: 4.9,
      views: "18.8k",
      isNew: true,
      type: "manga",
      status: "COMPLETED",
      genres: ["action", "comedy"],
      img: "./manga-art/sakamoto_days.jpg",
      chapters: [
        {
          id: "sd-1",
          title: "chapter 262",
          pages: 19,
          source: "/manga-source/chapter_262-sakamoto_days.pdf",
          type: "pdf",
        },
      ],
    },
    {
      title: "Komi Can't Communicate",
      demo: "shounen",
      ch: "Ch. 288",
      desc: "Timid Tadano is a total wallflower, and that's just the way he likes it. But all that changes when he finds himself alone in a classroom on the first day of high school with the legendary Komi. He quickly realizes she isn't aloof - she's just super awkward. Now he's made it his mission to help her on her quest to make 100 friends.",
      rating: 4.9,
      views: "18.8k",
      isNew: true,
      type: "manga",
      status: "COMPLETED",
      genres: ["romance", "slice of life", "comedy"],
      img: "./manga-art/komi_cant_communicate.jpg",
      chapters: [
        {
          id: "kcc-1",
          title: "Chapter 288: Rumiko-chan and Kometani-kun",
          pages: 12,
          source:
            "/manga-source/Komi-san_wa_Komyushou_Desu.-Ch.288-Rumiko-chan_and_Kometani-kun.pdf",
          type: "pdf",
        },
      ],
    },
    {
      title: "Cat Companions Maruru and Hachi",
      demo: "seinen",
      desc: "Maruru lived a pampered life till one day, he ran after a flock of sparrows and couldn't find his way back home. He encounters Hachi, a tough stray, who says he doesn't need a spoiled house cat on his territory and chases him away. But then Maruru helps Hachi out of a jam, and they team up to face life on the street together.",
      ch: "Ch. 259",
      rating: 4.9,
      views: "18.8k",
      isNew: true,
      type: "manga",
      status: "ONGOING",
      genres: ["Comedy", "slice of life"],
      img: "./manga-art/cat_companions_maruru_and_hachi.jpg",
      chapters: [
        {
          id: "cat-1",
          title: "Chapter 2: know-how for the day-to-day life",
          pages: 23,
          source: "/manga-source/chapter_2-cat.pdf",
          type: "pdf",
        },
        {
          id: "cat-1",
          title: "Chapter 1: Maruru and Hachi",
          pages: 32,
          source: "/manga-source/chapter_1-cat.pdf",
          type: "pdf",
        },
      ],
    },
    {
      title: "Marriage Toxin",
      decs: "Poison Master Hikaru Gero is about to take on his most challenging assignment yet—getting married! But after training his entire life to become one of the world’s deadliest assassins, Gero couldn’t be more clueless when it comes to the art of dating. Thankfully, marriage swindler Mei Kinosaki knows everything there is to know about love, and together, this unlikely pair is going to do whatever it takes to get Gero hitched—even if they have to take on the entire criminal underworld in the process!",
      demo: "shounen",
      ch: "Ch. 259",
      rating: 4.9,
      views: "18.8k",
      isNew: true,
      type: "manga",
      status: "COMPLETED",
      genres: ["drama", "comedy", "romance"],
      img: "./manga-art/marriage_toxin.jpg",
      chapters: [
        {
          id: "mt-1",
          title: "Chapter 1: Maruru and Hachi",
          pages: 32,
          source: "/manga-source/chapter_1-Marriage-Toxic.pdf",
          type: "pdf",
        },
      ],
    },
    {
      title: "Kaiju No. 8",
      demo: "shounen",
      desc: "Kafka Hibino is a 32-year-old member of the Professional Kaiju Cleanup Corp. His job as a Monster Sweeper is to chop up and dispose of Kaiju killed by the Defense Force. Kafka was also childhood friends with Mina Ashiro who he made a vow with to join the Defense Force together and protect Japan from Kaiju. However, Kafka failed the entrance exam numerous times and quit on his dreams of being a member of the Defense Force while Mina went on to become the captain of the Defense Force’s 3rd Division.",
      ch: "Ch. 129",
      rating: 4.5,
      views: "18.8k",
      isNew: true,
      type: "manga",
      status: "COMPLETED",
      genres: ["Comedy", "horror", "sci-fi"],
      img: "./manga-art/kaiju_no_8.jpg",
      chapters: [
        {
          id: "kn8-1",
          title: "Chapter 1: The Kaiju No. 8",
          pages: 54,
          source: "/manga-source/chapter_1-Kaiju-No-8.pdf",
          type: "pdf",
        },
      ],
    },

    // ── MANHWA ───────────────────────────────────────────────────────────────
    {
      title: "Solo Leveling",
      demo: "shounen",
      desc: "E-class hunter Jinwoo Sung is the weakest of them all. Looked down on by everyone, he has no money, no abilities to speak of, and no other job prospects. So when his party finds a hidden dungeon, he's determined to use this chance to change his life for the better...but the opportunity he finds is a bit different from what he had in mind...",
      ch: "Ch. 200",
      rating: 4.9,
      views: "18.2k",
      isNew: true,
      type: "manhwa",
      status: "COMPLETED",
      genres: ["Action", "Adventure"],
      img: "./manga-art/solo_leveling.jpg",
      chapters: [
        {
          id: "sl-1",
          title: "Chapter 200",
          pages: 126,
          source: "/manga-source/chapter_200-Solo-Leveling.pdf",
        },
        {
          id: "sl-1",
          title: "Chapter 2",
          pages: 53,
          source: "/manga-source/chapter_1-Solo-Leveling.pdf",
        },
        {
          id: "sl-1",
          title: "Chapter 1",
          pages: 36,
          source: "/manga-source/chapter_0-Solo-Leveling.pdf",
        },
      ],
    },
    {
      title: "WINDBREAKER",
      demo: "shounen",
      ch: "Ch. 344",
      desc: "Jay's the perfect student. He's got straight As and he's the student body president. But after being coerced into joining the school's biking team, the Hummingbird Crew, he discovers a whole new world outside of studying. What new adventures will he face outside the comfort of his textbooks?",
      rating: 4.5,
      views: "15.5k",
      isNew: true,
      type: "manhwa",
      status: "CANCELLED",
      genres: ["sport", "comedy", "drama"],
      img: "./manga-art/windbreaker.jpg",
      chapters: [
        {
          id: "wb-2",
          title: "Chapter 1: Episode1",
          source: "/manga-source/S1-Episode1_WindBreaker.pdf",
          pages: 24,
        },
        {
          id: "wb-1",
          title: "Chapter 1: Episode0",
          source: "/manga-source/S1-Episode0_WindBreaker.pdf",
          pages: 24,
        },
      ],
    },
    {
      title: "Lookism",
      demo: "seinen",
      ch: "Ch. 608",
      desc: "Daniel is an unattractive loner who wakes up in a different body. Now tall, handsome, and cooler than ever in his new form, Daniel aims to achieve everything he couldn't before. How far will he go to keep his body... and his secrets?",
      rating: 4.9,
      views: "12.2k",
      isNew: true,
      type: "manhwa",
      status: "ONGOING",
      genres: ["Comedy", "drama"],
      img: "./manga-art/lookism.jpg",
      chapters: [
        {
          id: "lookism-2",
          title: "Chapter 2: ",
          source: "/manga-source/chapter_2-Lookism.pdf",
          pages: 142,
        },
        {
          id: "lookism-1",
          title: "Chapter 1: ",
          source: "/manga-source/chapter_1-Lookism.pdf",
          pages: 114,
        },
      ],
    },
    {
      title: "Operation: True Love",
      desc: "It's hard dating someone who won't give you the time of day. Su-ae Shim knows that better than anyone, having dated her indifferent boyfriend, Minu Kang, for years. She sometimes wishes she could be more like her charismatic stepsister, Ra-im, who seems to have it all. But life takes a turn for the weird when Su-ae discovers Jellypop, a sentient flip phone, in her locker. Jellypop has a lot to say about her love life, especially as Su-ae drifts further away from Minu and finds herself running into Minu’s friend, Eunhyeok. Add to the mix a growing suspicion that Minu and Ra-im might be more than friends, and Su-ae might need a miracle to navigate the ups and downs of high school romance!",
      ch: "Ch. 134",
      rating: 5.0,
      views: "22.0k",
      isNew: true,
      type: "manhwa",
      status: "ONGOING",
      genres: ["drama", "romance"],
      img: "./manga-art/Operation_True_Love.jpg",
      chapters: [
        {
          id: "otl-1",
          title: "Chapter 0",
          source: "/manga-source/chapter_0-Operation_True_Love.pdf",
          pages: 73,
        },
      ],
    },
    {
      title: "The Regressed Son of a Duke is an Assassin",
      demo: "shounen",
      decs: "Cyan Vert, the illegitimate son of the Duke and the empire's greatest assassin, is betrayed by the righteous brother whose shadow he's always lived in. But just before the fatal blow strikes his throat, Cyan awakes to find he's just a boy again. The young lord has been reborn, and this time, he's not going to live in anyone's shadow!",
      ch: "Ch. 135",
      rating: 4.9,
      views: "5.5k",
      isNew: true,
      type: "manhwa",
      status: "ONGOING",
      genres: ["Action", "Adventure", "Drama"],
      img: "./manga-art/the_regressed_son_of_a_duke_is_an_assassin.jpg",
      chapters: [
        {
          id: "rg-1",
          title: "Chapter 130",
          source: "/manga-source/chapter_130-son.pdf",
          pages: 121,
        },
      ],
    },
    {
      title: "The Knight Who Only Lives Today",
      ch: "Ch. 111",
      rating: 4.9,
      views: "9.2k",
      isNew: false,
      type: "manhwa",
      img: "./manga-art/the_knight_who_only_lives_today.jpg",
    },

    // ── NOVEL ────────────────────────────────────────────────────────────────
    {
      title: "Omniscient Reader's Viewpoint",
      ch: "Vol. 6",
      rating: 4.9,
      views: "11.2k",
      isNew: false,
      type: "novel",
      img: "./manga-art/omniscient_reader.jpg",
      chapters: [
        {
          id: "orv-1",
          title: "Chapter 1",
          source: "/manga-source/chapter_1-reader.pdf",
          pages: 121,
        },
      ],
    },
    {
      title: "The Beginning After the End",
      ch: "Vol. 9",
      rating: 4.8,
      views: "9.8k",
      isNew: true,
      type: "novel",
      img: "./manga-art/tbate.jpg",
      chapters: [
        {
          id: "bt-1",
          title: "Chapter 1",
          source: "/manga-source/chapter_1-begin.pdf",
          pages: 21,
        },
      ],
    },

    {
      title: "Youkoso Jitsuryoku Shijou Shugi no Kyoushitsu e",
      ch: "Vol. 3",
      rating: 4.8,
      views: "7.1k",
      isNew: false,
      type: "novel",
      img: "./manga-art/youkoso_jitsuryoku_shijou_shugi_no_kyoushitsu_e.jpg",
      chapters: [
        {
          id: "yks-1",
          title: "Chapter 1",
          source: "/manga-source/chapter_1-yokoso.pdf",
          pages: 2,
        },
      ],
    },
  ],

  trendingData: [
    {
      title: "The Eminence in Shadow",
      ch: "Ch. 1",
      rating: 4.9,
      views: "15.4k",
      isNew: true,
      img: "./manga-art/Kage no Jitsuryokusha ni Naritakute!.jpg",
      chapters: [
        {
          id: "eis-1",
          title: "Chapter 1: The Eminence in Shadow!",
          pages: 0,
          source:
            "/manga-source/Kage no Jitsuryokusha ni Naritakute! - Ch. 1.pdf",
          type: "pdf",
        },
      ],
    },
    {
      title: "Attack on Titan",
      ch: "Ch. 139",
      rating: 5.0,
      views: "25.5k",
      isNew: false,
      img: "./manga-art/attack_on_titan.jpg",

      chapters: [
        {
          id: "aot-139",
          title: "Chapter 139: Toward the Tree on That Hill",
          pages: 20,
        },
        { id: "aot-138", title: "Chapter 138: A Long Dream", pages: 18 },
        { id: "aot-137", title: "Chapter 137: Titans", pages: 16 },
        {
          id: "aot-1",
          title: "Chapter 1: To You, 2000 Years From Now",
          pages: 25,
        },
      ],
    },
    {
      title: "Solo Leveling",
      ch: "Ch. 179",
      rating: 4.9,
      views: "18.2k",
      isNew: false,
      img: "./manga-art/solo_leveling.jpg",
      chapters: [
        {
          id: "sl-179",
          title: "Chapter 179: Epilogue finale",
          pages: 15,
        },
        {
          id: "sl-178",
          title: "Chapter 178: The Monarch of Shadows",
          pages: 12,
        },
        {
          id: "sl-1",
          title: "Chapter 1: The Courage of the Weakest",
          pages: 18,
        },
      ],
    },
    {
      title: "Chainsaw Man",
      ch: "Ch. 131",
      rating: 4.8,
      views: "13.1k",
      isNew: true,
      img: "./manga-art/chainsaw_man.jpg",
      chapters: [
        { id: "csm-131", title: "Chapter 131: Taste of Shit", pages: 16 },
        { id: "csm-130", title: "Chapter 130: Kill Building", pages: 14 },
        { id: "csm-1", title: "Chapter 1: Dog & Chainsaw", pages: 22 },
      ],
    },
    {
      title: "One Piece",
      ch: "Ch. 1183",
      rating: 4.5,
      views: "15.5k",
      isNew: true,
      img: "./manga-art/one_piece.jpg",
    },
    {
      title: "WINDBREAKER",
      ch: "Ch. 344",
      rating: 4.5,
      views: "15.5k",
      isNew: false,
      img: "./manga-art/windbreaker.jpg",
      chapters: [
        {
          id: "wb-1",
          title: "Chapter 1: Episode0",
          source: "/manga-source/S1-Episode0_WindBreaker.pdf",
          pages: 24,
          type: "pdf",
        },
      ],
    },
    {
      title: "Lookism",
      ch: "Ch. 608",
      rating: 4.9,
      views: "12.2k",
      isNew: false,
      img: "./manga-art/lookism.jpg",
    },
    {
      title: "Operation: True Love",
      ch: "Ch. 134",
      rating: 5.0,
      views: "22.0k",
      isNew: false,
      img: "./manga-art/Operation_True_Love.jpg",
    },
    {
      title: "Blue Lock: Episode Nagi",
      ch: "Ch. 215",
      rating: 4.7,
      views: "9.2k",
      isNew: true,
      img: "./manga-art/blue_lock_episode_nagi.jpg",
    },
    {
      title: "Naruto",
      ch: "Ch. 700",
      rating: 4.6,
      views: "50.1k",
      isNew: false,
      img: "  ./manga-art/naruto.jpg",
    },
    {
      title: "JoJo's Bizarre Adventure - Part 1 - Phantom Blood",
      ch: "Ch. 44",
      rating: 4.5,
      views: "10.8k",
      isNew: false,
      img: "./manga-art/jojo_phantom_blood.jpg",
    },
    {
      title: "Nana",
      ch: "Ch. 21",
      rating: 4.6,
      views: "50.1k",
      isNew: false,
      img: "./manga-art/nana.jpg",
    },
    {
      title: "Maid-sama!",
      ch: "Ch. 85",
      rating: 4.6,
      views: "40.1k",
      isNew: false,
      img: "./manga-art/maid_sama.jpg",
    },
    {
      title: "Dragon Ball",
      ch: "Ch. 519",
      rating: 4.7,
      views: "45.5k",
      isNew: false,
      img: "./manga-art/dragonball.jpg ",
    },
    {
      title: "Tokyo Ghoul",
      ch: "Ch. 143",
      rating: 4.8,
      views: "12.2k",
      isNew: false,
      img: "./manga-art/tokyo_ghoul.jpg",
    },
    {
      title: "Death Note",
      ch: "Ch. 108.4",
      rating: 4.9,
      views: "30.5k",
      isNew: false,
      img: "./manga-art/death_note.jpg ",
    },
    {
      title: "Haikyuu!!",
      ch: "Ch. 402.3",
      rating: 4.8,
      views: "11.5k",
      isNew: false,
      img: "./manga-art/haikyuu.jpg",
    },
    {
      title: "The Summer Hikaru Died",
      ch: "Ch. 40.3",
      rating: 3.5,
      views: "6.2k",
      isNew: true,
      img: "./manga-art/the_summer_hikaru_died.jpg",
    },
    {
      title: "Monster",
      ch: "Ch. 162",
      rating: 4.4,
      views: "4.2k",
      isNew: true,
      img: "./manga-art/monster.jpg",
    },
    {
      title: "Vinland Saga",
      ch: "Ch. 220",
      rating: 4.9,
      views: "8.5k",
      isNew: false,
      img: "./manga-art/vinland_saga.jpg",
    },
    {
      title: "Vagabond",
      ch: "Ch. 327",
      rating: 5.0,
      views: "7.1k",
      isNew: false,
      img: "./manga-art/vagabond.jpg",
    },
    {
      title: "Berserk",
      ch: "Ch. 373",
      rating: 5.0,
      views: "25.2k",
      isNew: true,
      img: "./manga-art/berserk.jpg",
    },
    {
      title: "Blood-C",
      ch: "Ch. 17",
      rating: 4.8,
      views: "22.5k",
      isNew: true,
      img: "./manga-art/blood_c.jpg",
    },
    {
      title: "Slam Dunk",
      ch: "Ch. 276",
      rating: 4.9,
      views: "10.1k",
      isNew: false,
      img: "  ./manga-art/slam_dunk.jpg",
    },
    {
      title: "The Regressed Son of a Duke is an Assassin",
      ch: "Ch. 127",
      rating: 4.9,
      views: "5.5k",
      isNew: false,
      img: "./manga-art/the_regressed_son_of_a_duke_is_an_assassin.jpg",
    },
    {
      title: "The Knight Who Only Lives Today",
      ch: "Ch. 111",
      rating: 4.9,
      views: "9.2k",
      isNew: true,
      img: "./manga-art/the_knight_who_only_lives_today.jpg ",
    },
    {
      title: "Sakamoto Days",
      ch: "Ch. 259",
      rating: 4.9,
      views: "18.8k",
      isNew: false,
      img: "./manga-art/sakamoto_days.jpg",
    },
    {
      title: "KIKI",
      ch: "Ch. 259",
      rating: 4.9,
      views: "18.8k",
      isNew: false,
      img: "./manga-art/sakamoto_days.jpg",
    },
    {
      title: "Sakamoto Days",
      ch: "Ch. 259",
      rating: 4.9,
      views: "18.8k",
      isNew: false,
      img: "./manga-art/sakamoto_days.jpg",
    },
    {
      title: "Sakamoto Days",
      ch: "Ch. 259",
      rating: 4.9,
      views: "18.8k",
      isNew: false,
      img: "./manga-art/sakamoto_days.jpg",
    },
    {
      title: "Sakamoto Days",
      ch: "Ch. 259",
      rating: 4.9,
      views: "18.8k",
      isNew: false,
      img: "./manga-art/sakamoto_days.jpg",
    },
  ],
};
